#
# This file contains configuration flags to customize your site you'll find settings for sass, js, etc in the gruntfile.js
#

# Name of your site (displayed in the header)
name: Site Name

# Short bio or description (displayed in the header)
description: Site Description

# Global Navigation
navigation:
- text: Group1
  url : group1
  sublinks:
    - subtext: Link1
      suburl : /Link1.html
    - subtext: Link2
      suburl : /Link2.html

- text: Group2
  url : group2
  sublinks:
    - subtext: Link1
      suburl : /Link1.html
    - subtext: Link2
      suburl : /Link2.html


# Includes an icon in the footer for each username you enter (be sure to include them in the footer)
social-links:
  dribbble: hansE
  twitter: haahns
  codepen: hans

  linkedin: hansenge
  github: https://github.com/HansEngebretsen


# Uncomment and enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: UA-2110908-2


#
# !! You're much less likely to want to edit anyting from here on out !!
#

# Sets source and desitnation directories for input/output
destination: htdocs/
source: src/

markdown: redcarpet
highlighter: pygments
permalink: /:title/
baseurl: /

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem



# Tell jekyll not to mess with these files in the output dir - they're generated by Grunt,
keep_files:
    - css
    - js/build
    - sass

# Don't output anything in the _parts directory
collections:
   parts:
      output: false

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Gruntfile.js
    - node_modules
    - js
    - sass

